[package]
name = "wallpaper_changer"
version = "0.2.0"
edition = "2024"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
ureq = { version = "3.0.11", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
actix-web = "4.11.0"