[package]
name = "wallpaper_changer"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.10", features = ["image"] }
tokio = { version = "1.0", features = ["full"] }
ureq = { version = "3.0.11", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }