[package]
name = "wallpaper_changer"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk4 = { version = "0.9.6", features = ["v4_6"] }
tokio = { version = "1.0", features = ["full"] }
ureq = { version = "3.0.11", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }